config/routes.rb
Rails.application.routes.draw do
    resources :posts

    root 'pages#home'

    get :home, :math, :form, :about, controller: 'pages'

    # get :about, controller: 'pages', path: :me

    post :about, controller: :pages

    # the " path: :method_name " can easily change the link we set in every actions which have the link

end

app/models/post.rb
#encoding: UTF-8
class Post < ActiveRecord::Base
	has_and_belongs_to_many :tags
	validates :title, :content, presence: true
	before_validation :set_content_from_title
	# validate :title_must_start_with_T
	
	def set_content_from_title
		self.content = title if content.blank?
	end


	def title_must_start_with_T
		unless title.to_s.start_with? 'T'
			errors.add(:title, 'must start with \"T\"')			
		end
	end

	belongs_to :user
end

app/models/post_uby.rb
#encoding: UTF-8
class Post < ActiveRecord::Base
  validates :title, :content, presence: true
  validate :title_must_start_with_x
  before_validation :set_content_from_title

  def title_must_start_with_x
    unless title.to_s.start_with? 'X'
      errors.add :title, 'must start with "X"'
    end
  end

  def set_content_from_title
    self.content = title if content.blank?
  end

  belongs_to :user



=begin
  validate do
    unless title.to_s.start_with? 'X'
      errors.add :title, 'must start with "X"'
    end
  end
=end

  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	# to make all views in this controller has the same layout: 
	# layout 'layout_name'
	# if we didn't setting which layout will render,
	# it will redner application.html.erb

    def home
    	# to make one method has layout:
    	# render layout: 'layout_name'
    end

    def about
        @name = "#{params[:first_name]} #{params[:last_name]}"
        # render layout: 'admin'
    end

    def math
        @numbers = (1..46).to_a.sample(6)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
  end

  def show
  	@post = Post.find params[:id]
  end

  # why we have to change method "new" into "create"? isn't method "new" came more earlier than method "create"?
  def create
    #we can get title and content value from view, use these two parameters initialize Post object
    @post = Post.new title: params[:title], content: params[:content]

    if @post.save
      redirect_to @post
    else
      render :new
    end

  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/navbar_helper.rb
module NavbarHelper
	def nav_li text, path
		class_name = request.path == path ? :class_name : nil
		content_tag :li, link_to(text, path), class: class_name
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/admin.html.erb
<h1>後台</h1> from new layout <br>
<%= link_to 'Home', home_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ruby2</title>
  <!-- <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %> -->
  <!-- <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->

  <%= stylesheet_link_tag 'style' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/navbar', line_number: 3 %>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>


<p>input from form:</p>
<%= params[:name] %>
<!-- we can get this " params[:name] " from form or the url path -->

<hr>

app/views/pages/form.html.erb
<%= form_tag about_path do %>
	<input type="text" name="name">
	<input type="submit">
<% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/math.html.erb
<%= 1 + 1 %>

<ul>
	<% @numbers.each do |i| %>
	<li>
		<%= i %></li>
	<% end %>
</ul>

<a href="<%= about_path %>">連結測試: About to me</a>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

<div>
	<ol>
	<% @posts.each do |post| %>
			<li><%= link_to post.title, post %></li>
	<% end %>
	</ol>
</div>

<%= link_to "create new post", new_post_path %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

<%= form_tag posts_path do %>
	<%= text_field_tag :title %> <br>
	<%= text_area_tag :content %>
	<input type="submit">
<% end %>

<%= link_to "back home", posts_path %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

<h1><%= @post.title %></h1>
<p><%= @post.content %></p>

<%= link_to 'Go Back with path', posts_path %>

app/views/shared/_navbar.html.erb
<ul>
	<%= nav_li 'Home', root_path %>
	<%= nav_li 'About', about_path %>
	<%= nav_li 'Math', math_path %>
	<%= nav_li 'Form', form_path %>
</ul>

<!-- the partial's name has to be start at '_' (under line)
	if the render page didn't specify the parent dir, it will find the partail in the controller which the view belongs to -->